name: Check Documentation Generation

on:
  pull_request:
    branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - name: lint TS
        run: npm run lint

      - name: compile TS
        run: tsc

      - name: Generate Documentation
        run: npm run generate-zip
